name: Publish VSCode Extension

on:
  push:
    branches:
      - main

env:
  VSCODE_EXT_PUBLISH_TOKEN: ${{ secrets.VS_MARKETPLACE_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Publish VSCode extension
      run: |
        npm install 
        npm install -g @vscode/vsce
        vsce package
        vsce publish -p ${{ env.VSCODE_EXT_PUBLISH_TOKEN }}

          
          
