name: Publish VSCode Extension

on:
  push:
    branches:
      - main

env:
  VSCODE_EXT_PUBLISH_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Publish VSCode extension
      run: |
        npm install @vscode/vsce
        vsce package
        vsce publish -p ${{ env.VSCODE_EXT_PUBLISH_TOKEN }}
      env:
        NODE_AUTH_TOKEN: ${{ env.VSCODE_EXT_PUBLISH_TOKEN }}

          
          
