name: Publish VSCode Extension

on:
  push:
    branches:
      - main

env:
  VSCODE_EXT_PUBLISH_TOKEN: ${{ secrets.VS_MARKETPLACE_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish VSCode extension
      uses: actions/npm@v1
      with:
        args: publish
      env:
        NODE_AUTH_TOKEN: ${{ env.VSCODE_EXT_PUBLISH_TOKEN }}

          
          
